name: Compile boards
run-name: Compiling all boards
on: [push]
jobs:
  Compile_brucon:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.2
        target: esp32s2
        path: 'esp32-s2-hmi-devkit-1/examples/smart-panel'
    - run: make all

